"""Bazel macros for caching code generation in KubeVirt.

This module provides reusable macros to wrap code generation tools
so their outputs can be cached by Bazel.
"""

def _run_generator_impl(ctx):
    """Implementation for running a generator tool and capturing outputs."""
    outputs = ctx.outputs.outs
    generator = ctx.executable.generator
    args = ctx.attr.args

    # Build the command
    cmd_args = [generator.path] + args

    # Add output directory if specified
    if ctx.attr.output_dir_arg:
        cmd_args.extend([ctx.attr.output_dir_arg, outputs[0].dirname])

    ctx.actions.run_shell(
        inputs = ctx.files.srcs + [generator],
        outputs = outputs,
        command = " ".join(cmd_args),
        env = ctx.attr.env,
        mnemonic = "RunGenerator",
        progress_message = "Generating %s" % ctx.attr.name,
    )

    return [DefaultInfo(files = depset(outputs))]

# Run a generator tool with caching
run_generator = rule(
    implementation = _run_generator_impl,
    attrs = {
        "generator": attr.label(
            executable = True,
            cfg = "exec",
            mandatory = True,
            doc = "The generator tool to run",
        ),
        "srcs": attr.label_list(
            allow_files = True,
            doc = "Source files that the generator depends on",
        ),
        "args": attr.string_list(
            doc = "Arguments to pass to the generator",
        ),
        "outs": attr.output_list(
            mandatory = True,
            doc = "Output files generated by the tool",
        ),
        "output_dir_arg": attr.string(
            doc = "Argument flag for specifying output directory",
        ),
        "env": attr.string_dict(
            doc = "Environment variables for the generator",
        ),
    },
)

def manifest_generator(name, type, output, namespace = None, pull_policy = None, feature_gates = None, infra_replicas = None, **kwargs):
    """Generate a manifest file using resource-generator.

    Args:
        name: Name of the target
        type: The type of resource to generate (e.g., "priorityclass", "kv", "kv-cr", "operator-rbac")
        output: Output file path
        namespace: Optional namespace parameter
        pull_policy: Optional image pull policy
        feature_gates: Optional feature gates
        infra_replicas: Optional infra replicas
        **kwargs: Additional arguments to pass to genrule
    """
    args = ["--type=" + type]

    if namespace:
        args.append("--namespace=" + namespace)
    if pull_policy:
        args.append("--pullPolicy=" + pull_policy)
    if feature_gates:
        args.append("--featureGates=" + feature_gates)
    if infra_replicas:
        args.append("--infraReplicas=" + infra_replicas)

    native.genrule(
        name = name,
        srcs = [],
        outs = [output],
        cmd = "$(location //tools/resource-generator) " + " ".join(args) + " > $@",
        tools = ["//tools/resource-generator"],
        **kwargs
    )

def csv_generator(
        name,
        output,
        operator_image_version = "{{.DockerTag}}",
        csv_created_at = "{{.CreatedAt}}",
        csv_version = "{{.CsvVersion}}",
        replaces_csv_version = "{{.ReplacesCsvVersion}}",
        docker_prefix = "{{.DockerPrefix}}",
        kubevirt_logo = "{{.KubeVirtLogo}}",
        kubevirt_version = "{{.DockerTag}}",
        namespace = "{{.CSVNamespace}}",
        pull_policy = "{{.ImagePullPolicy}}",
        verbosity = "{{.Verbosity}}",
        **kwargs):
    """Generate an operator CSV file using csv-generator.

    Args:
        name: Name of the target
        output: Output file path
        operator_image_version: Version of the operator image
        csv_created_at: Timestamp when CSV was created
        csv_version: Version of the CSV
        replaces_csv_version: Version of CSV this replaces
        docker_prefix: Docker registry prefix
        kubevirt_logo: Logo for KubeVirt
        kubevirt_version: Version of KubeVirt
        namespace: Namespace for the CSV
        pull_policy: Image pull policy
        verbosity: Verbosity level
        **kwargs: Additional arguments to pass to genrule
    """

    # Use placeholder versions that will be replaced
    fake_csv_version = "2222.2222.2222"
    fake_replaces_csv_version = "1111.1111.1111"

    native.genrule(
        name = name,
        srcs = [],
        outs = [output],
        cmd = """
$(location //tools/csv-generator:csv-generator) \
    --operatorImageVersion="{operator_image_version}" \
    --csvCreatedAtTimestamp={csv_created_at} \
    --csvVersion="{fake_csv_version}" \
    --dockerPrefix={docker_prefix} \
    --kubevirtLogo={kubevirt_logo} \
    --kubeVirtVersion={kubevirt_version} \
    --namespace={namespace} \
    --pullPolicy={pull_policy} \
    --replacesCsvVersion="{fake_replaces_csv_version}" \
    --verbosity={verbosity} | \
    sed 's/{fake_csv_version}/{csv_version}/g' | \
    sed 's/{fake_replaces_csv_version}/{replaces_csv_version}/g' > $@
""".format(
            operator_image_version = operator_image_version,
            csv_created_at = csv_created_at,
            csv_version = csv_version,
            replaces_csv_version = replaces_csv_version,
            fake_csv_version = fake_csv_version,
            fake_replaces_csv_version = fake_replaces_csv_version,
            docker_prefix = docker_prefix,
            kubevirt_logo = kubevirt_logo,
            kubevirt_version = kubevirt_version,
            namespace = namespace,
            pull_policy = pull_policy,
            verbosity = verbosity,
        ),
        tools = ["//tools/csv-generator"],
        **kwargs
    )

def vms_generator(name, output_dir, container_prefix = "registry:5000/kubevirt", container_tag = "devel", **kwargs):
    """Generate example VM files using vms-generator.

    Args:
        name: Name of the target
        output_dir: Output directory for generated files
        container_prefix: Docker registry prefix
        container_tag: Docker tag
        **kwargs: Additional arguments to pass to genrule
    """
    native.genrule(
        name = name,
        srcs = [],
        outs = [output_dir],
        cmd = """
mkdir -p $@
$(location //tools/vms-generator) \
    --container-prefix={prefix} \
    --container-tag={tag} \
    --generated-vms-dir=$@
""".format(
            prefix = container_prefix,
            tag = container_tag,
        ),
        tools = ["//tools/vms-generator"],
        **kwargs
    )

def openapi_spec_generator(name, output, **kwargs):
    """Generate OpenAPI spec using openapispec tool.

    Args:
        name: Name of the target
        output: Output file path
        **kwargs: Additional arguments to pass to genrule
    """
    native.genrule(
        name = name,
        srcs = [],
        outs = [output],
        cmd = "$(location //tools/openapispec) --dump-api-spec-path $@",
        tools = ["//tools/openapispec"],
        **kwargs
    )

def doc_generator(name, output, **kwargs):
    """Generate metrics documentation using doc-generator.

    Args:
        name: Name of the target
        output: Output file path
        **kwargs: Additional arguments to pass to genrule
    """
    native.genrule(
        name = name,
        srcs = [],
        outs = [output],
        cmd = "$(location //tools/doc-generator) > $@",
        tools = ["//tools/doc-generator"],
        **kwargs
    )
