---
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshotSchedule
metadata:
  name: daily-backup
spec:
  retention:
    maxCount: 7
  schedule: 0 0 * * *
  snapshotTemplate:
    annotations:
      description: Daily backup snapshot
    labels:
      backup-type: daily
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: my-vm
