// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (VirtualMachineSnapshot) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "VirtualMachineSnapshot defines the operation of snapshotting a VM\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"status": "+optional",
	}
}

func (VirtualMachineSnapshotSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                "VirtualMachineSnapshotSpec is the spec for a VirtualMachineSnapshot resource",
		"deletionPolicy":  "+optional",
		"failureDeadline": "This time represents the number of seconds we permit the vm snapshot\nto take. In case we pass this deadline we mark this snapshot\nas failed.\nDefaults to DefaultFailureDeadline - 5min\n+optional",
	}
}

func (SourceIndication) SwaggerDoc() map[string]string {
	return map[string]string{
		"":           "SourceIndication provides an indication of the source VM with its description message",
		"indication": "Indication is the indication type",
		"message":    "Message provides a description message of the indication",
	}
}

func (VirtualMachineSnapshotStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                                  "VirtualMachineSnapshotStatus is the status for a VirtualMachineSnapshot resource",
		"sourceUID":                         "+optional",
		"virtualMachineSnapshotContentName": "+optional",
		"creationTime":                      "+optional\n+nullable",
		"phase":                             "+optional",
		"readyToUse":                        "+optional",
		"error":                             "+optional",
		"conditions":                        "+optional",
		"indications":                       "Deprecated: Use SourceIndications instead. This field will be removed in a future version.\n+optional\n+listType=set",
		"sourceIndications":                 "+optional\n+listType=atomic",
		"snapshotVolumes":                   "+optional",
	}
}

func (SnapshotVolumesLists) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                "SnapshotVolumesLists includes the list of volumes which were included in the snapshot and volumes which were excluded from the snapshot",
		"includedVolumes": "+optional\n+listType=set",
		"excludedVolumes": "+optional\n+listType=set",
	}
}

func (Error) SwaggerDoc() map[string]string {
	return map[string]string{
		"":        "Error is the last error encountered during the snapshot/restore",
		"time":    "+optional",
		"message": "+optional",
	}
}

func (Condition) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                   "Condition defines conditions",
		"lastProbeTime":      "+optional\n+nullable",
		"lastTransitionTime": "+optional\n+nullable",
		"reason":             "+optional",
		"message":            "+optional",
	}
}

func (VirtualMachineSnapshotList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VirtualMachineSnapshotList is a list of VirtualMachineSnapshot resources\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}

func (VirtualMachineSnapshotContent) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "VirtualMachineSnapshotContent contains the snapshot data\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"status": "+optional",
	}
}

func (VirtualMachineSnapshotContentSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":              "VirtualMachineSnapshotContentSpec is the spec for a VirtualMachineSnapshotContent resource",
		"volumeBackups": "+optional",
	}
}

func (VirtualMachine) SwaggerDoc() map[string]string {
	return map[string]string{
		"spec":   "VirtualMachineSpec contains the VirtualMachine specification.",
		"status": "Status holds the current state of the controller and brief information\nabout its associated VirtualMachineInstance",
	}
}

func (SourceSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":               "SourceSpec contains the appropriate spec for the resource being snapshotted",
		"virtualMachine": "+optional",
	}
}

func (PersistentVolumeClaim) SwaggerDoc() map[string]string {
	return map[string]string{
		"spec": "Spec defines the desired characteristics of a volume requested by a pod author.\nMore info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims\n+optional",
	}
}

func (VolumeBackup) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                   "VolumeBackup contains the data neeed to restore a PVC",
		"volumeSnapshotName": "+optional",
	}
}

func (VirtualMachineSnapshotContentStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                     "VirtualMachineSnapshotContentStatus is the status for a VirtualMachineSnapshotStatus resource",
		"creationTime":         "+optional\n+nullable",
		"readyToUse":           "+optional",
		"error":                "+optional",
		"volumeSnapshotStatus": "+optional",
	}
}

func (VirtualMachineSnapshotContentList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VirtualMachineSnapshotContentList is a list of VirtualMachineSnapshot resources\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}

func (VolumeSnapshotStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":             "VolumeSnapshotStatus is the status of a VolumeSnapshot",
		"creationTime": "+optional\n+nullable",
		"readyToUse":   "+optional",
		"error":        "+optional",
	}
}

func (VirtualMachineRestore) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "VirtualMachineRestore defines the operation of restoring a VM\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"status": "+optional",
	}
}

func (VirtualMachineRestoreSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":        "VirtualMachineRestoreSpec is the spec for a VirtualMachineRestoreresource",
		"target":  "initially only VirtualMachine type supported",
		"patches": "If the target for the restore does not exist, it will be created. Patches holds JSON patches that would be\napplied to the target manifest before it's created. Patches should fit the target's Kind.\n\nExample for a patch: {\"op\": \"replace\", \"path\": \"/spec/template/spec/domain/devices/interfaces/0/macAddress\", \"value\": \"00:00:5e:00:53:01\"}\n\n+optional\n+listType=atomic",
	}
}

func (VirtualMachineRestoreStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                   "VirtualMachineRestoreStatus is the spec for a VirtualMachineRestoreresource",
		"restores":           "+optional",
		"restoreTime":        "+optional",
		"deletedDataVolumes": "+optional",
		"complete":           "+optional",
		"conditions":         "+optional",
	}
}

func (VolumeRestore) SwaggerDoc() map[string]string {
	return map[string]string{
		"":               "VolumeRestore contains the data neeed to restore a PVC",
		"dataVolumeName": "+optional",
	}
}

func (VirtualMachineRestoreList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VirtualMachineRestoreList is a list of VirtualMachineRestore resources\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}

func (VirtualMachineSnapshotSchedule) SwaggerDoc() map[string]string {
	return map[string]string{
		"":       "VirtualMachineSnapshotSchedule defines a schedule for taking snapshots of VirtualMachines\n+genclient\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"status": "+optional",
	}
}

func (VirtualMachineSnapshotScheduleSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                 "VirtualMachineSnapshotScheduleSpec is the spec for a VirtualMachineSnapshotSchedule resource",
		"source":           "Source is the TypedLocalObjectReference of the VirtualMachine to snapshot.\nIf specified, takes precedence over VMSelector.\n+optional",
		"vmSelector":       "VMSelector is a LabelSelector to select VirtualMachines to snapshot.\nMultiple VMs can be selected using this field.\n+optional",
		"schedule":         "Schedule defines the cron expression for when snapshots should be taken.\nThe schedule is interpreted with respect to the UTC timezone.\nSupports standard cron expressions and pre-defined shortcuts:\n@hourly, @daily, @weekly, @monthly, @yearly",
		"disabled":         "Disabled when set to true makes the schedule inactive\n+optional",
		"retention":        "Retention defines the policy for retaining snapshots\n+optional",
		"snapshotTemplate": "SnapshotTemplate contains settings for the VirtualMachineSnapshots that are created\n+optional",
		"failurePolicy":    "FailurePolicy defines how to handle snapshot failures\n+optional",
	}
}

func (VirtualMachineSnapshotScheduleRetention) SwaggerDoc() map[string]string {
	return map[string]string{
		"":         "VirtualMachineSnapshotScheduleRetention defines the retention policy for scheduled snapshots",
		"expires":  "Expires is the length of time a snapshot should be retained.\nFormat is a duration string (e.g., \"168h\" for 1 week, \"720h\" for 30 days).\nWhen both Expires and MaxCount are set, snapshots are deleted when either\ncondition is met.\n+optional",
		"maxCount": "MaxCount is the maximum number of snapshots to retain per VirtualMachine.\nWhen this limit is reached, the oldest snapshot will be deleted.\nWhen both Expires and MaxCount are set, snapshots are deleted when either\ncondition is met.\n+optional",
	}
}

func (VirtualMachineSnapshotTemplateSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                "VirtualMachineSnapshotTemplateSpec contains settings for snapshots created by the schedule",
		"labels":          "Labels to add to each VirtualMachineSnapshot\n+optional",
		"annotations":     "Annotations to add to each VirtualMachineSnapshot\n+optional",
		"deletionPolicy":  "DeletionPolicy defines what to do with the VirtualMachineSnapshotContent\nwhen the VirtualMachineSnapshot is deleted\n+optional",
		"failureDeadline": "FailureDeadline is the time limit for a snapshot to complete.\nIf not specified, defaults to 5 minutes.\n+optional",
	}
}

func (VirtualMachineSnapshotScheduleStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                           "VirtualMachineSnapshotScheduleStatus is the status for a VirtualMachineSnapshotSchedule",
		"phase":                      "Phase is the current phase of the schedule\n+optional",
		"lastSnapshotTime":           "LastSnapshotTime is the time when the last snapshot was taken\n+optional\n+nullable",
		"nextSnapshotTime":           "NextSnapshotTime is the time when the next snapshot is scheduled\n+optional\n+nullable",
		"lastSuccessfulSnapshotName": "LastSuccessfulSnapshotName is the name of the last successfully completed snapshot\n+optional",
		"currentSnapshotCount":       "CurrentSnapshotCount is the current number of snapshots managed by this schedule\nper each VM when using VMSelector, or total when using Source\n+optional",
		"error":                      "Error contains the last error encountered by the controller\n+optional",
		"conditions":                 "Conditions represent the latest available observations of the schedule's state\n+optional\n+listType=atomic",
		"vmSnapshotStatuses":         "VMSnapshotStatuses contains the status of snapshots per VM when using VMSelector\n+optional\n+listType=atomic",
	}
}

func (VMSnapshotStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                     "VMSnapshotStatus contains snapshot status for a specific VM",
		"vmName":               "VMName is the name of the VirtualMachine",
		"lastSnapshotName":     "LastSnapshotName is the name of the last snapshot taken for this VM\n+optional",
		"lastSnapshotTime":     "LastSnapshotTime is when the last snapshot was taken for this VM\n+optional\n+nullable",
		"currentSnapshotCount": "CurrentSnapshotCount is the current number of snapshots for this VM\n+optional",
		"error":                "Error contains any error for this VM's snapshots\n+optional",
	}
}

func (VirtualMachineSnapshotScheduleList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VirtualMachineSnapshotScheduleList is a list of VirtualMachineSnapshotSchedule resources\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}
